# Generated by Django 3.2.9 on 2021-11-30 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя производителя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Страна производителя')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Основание фирмы')),
                ('date_of_death', models.DateField(blank=True, null=True, verbose_name='Велосипед произведен')),
            ],
            options={
                'verbose_name': 'Производителя(й)',
                'verbose_name_plural': 'Приозводители',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('summary', models.TextField(help_text='Enter a brief description of the bike', max_length=1000, verbose_name='Описание')),
                ('isbn', models.CharField(help_text=' Номера рамы расположены в разных местах <a href="https://www.sportek.in.ua/blogs/stati/gde-nanesen-seriynyy-nomer-velosipeda-ili-ego-ramy">Места распаложения</a>', max_length=13, unique=True, verbose_name='№ рамы')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Велосипед',
                'verbose_name_plural': 'Велосипеды',
                'ordering': ['title', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите подходящий пол человека (Мужской, Женский, Унисекс)', max_length=200, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите тип велосипеда (например, Горный, Шоссейный, BMX и т.д.', max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='BikeInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор этого конкретного велосипеда во всем гараже', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200, verbose_name='Коментарий')),
                ('due_back', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('status', models.CharField(blank=True, choices=[('d', 'Техническое обслуживание'), ('o', 'В изпользовании'), ('a', 'Доступный'), ('r', 'Зарезервирован')], default='d', help_text='Доступность Велосипеда', max_length=1, verbose_name='Статус')),
                ('bike', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.bike', verbose_name='Веловиспед')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Зарезервировал')),
            ],
            options={
                'verbose_name': 'Бронь велосипеда',
                'verbose_name_plural': 'Бронь велосипеда',
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Set bike as returned'),),
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='Sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sex', verbose_name='Тип рамы'),
        ),
        migrations.AddField(
            model_name='bike',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.author', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='bike',
            name='typ',
            field=models.ManyToManyField(help_text='Select a typ for this bike', to='catalog.Typ', verbose_name='Тип велосипеда'),
        ),
    ]
